import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "../ui/navbar";
import Footer from "../ui/footer";
import ClientSessionProvider from "../lib/client-session-provider";
import QueryProvider from "../lib/query-provider";
// import { getServerSession } from "next-auth";
// import { authOptions } from "../lib/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const dynamic = "force-static";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await getServerSession(authOptions);
  // console.log({ session });
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <div className="main">
            <div className="gradient" />
          </div>
          <ClientSessionProvider>
            <QueryProvider>
              <Navbar />
              <main className="relative container px-1 mt-10">{children}</main>
              <Footer />
            </QueryProvider>
          </ClientSessionProvider>
        </div>
      </body>
    </html>
  );
}
